<?
$dictionary = array (
  'Cerco' => 'Searching',
  'Cerco vicino a te' => 'Searching near you',
  'Cerco vicino alla posizione impostata' => 'Searching near the position in settings',
  'Risultati' => 'Results',
  'Per visualizzare i risultati vicino a te devi autorizzare l\\\'applicazione a sapere la tua posizione oppure imposta manualmente la posizione in cui cercare' => 'To view the results close to you you need to authorize the \\ \'application know your location, or manually set the location to search',
  'Inserisci almeno 2 caratteri' => 'Please enter at least 2 characters',
  'Nessun preferito' => 'No bookmarks',
  'Distanza' => 'distance',
  'Categorie' => 'categories',
  'Nessun risultato' => 'No results',
  'Voto' => 'Vote',
  'Checkins' => 'Checkins',
  'Tel' => 'Ph',
  'Fax' => 'Fax',
  'Email' => 'Email',
  'Sito web' => 'Website',
  'Mappa di' => 'Map of',
  'RIMUOVI DAI PREFERITI' => 'REMOVE FROM FAVORITES',
  'AGGIUNGI AI PREFERITI' => 'ADD TO FAVORITES',
  'CHECK-IN' => 'CHECK-IN',
  'VOTA' => 'VOTE',
  'MODIFICA' => 'MODIFICATION',
  'SEI IL TITOLARE' => 'YOU ARE THE OWNER',
  'Mappa nuova location' => 'Map new location',
  'Per aggiungere una location devi essere loggato' => 'To add a location you must be logged',
  'Ti vuoi loggare ora' => 'Do you want to login now',
  'Nessuna posizione impostata' => 'No location set',
  'imposta manualmente' => 'manually set',
  'Per impostare la tua posizione devi abilitare l\'applicazione a leggere la tua posizione' => 'To set your location you must enable the application to read your position',
  'OK' => 'OK',
  'NO' => 'NO',
  'Modifica la posizione' => 'Changing the position',
  'Controlla la posizione sulla mappa' => 'Check the location on the map',
  'Controlla il sito web, ricordati di inserire http://' => 'Check the web site, be sure to include http://',
  'Controlla la mail' => 'Check your mail',
  'Inserisci il nome' => 'Enter the name',
  'Inserisci il messaggio' => 'Enter the message',
  'Grazie per aver inviato il messaggio' => 'Thank you for sending the message',
  'Oggi hai già fatto il checkin quì' => 'Today you\'ve already done the checkin here',
  'Grazie per aver fatto il checkin' => 'Thanks for doing the checkin',
  'Per fare il checkin devi essere loggato' => 'To make the checkin must be logged in',
  'Rimosso dai preferiti' => 'Removed from my favorites',
  'Grazie di aver inserito tra i preferiti' => 'Thank you bookmarked',
  'Per inserire tra i preferiti devi essere loggato' => 'To insert a favorite you must be logged',
  'Per votare devi essere loggato' => 'To vote you must be logged in.',
  'Per accedere a facebook devi essere loggato' => 'To enter you must be logged in facebook',
  'accedi ora' => 'login now',
  'Per visualizzare i preferiti devi essere loggato' => 'To view the favorites you must be logged in.',
  'PagineBaby' => 'PagineBaby',
  'Facebook' => 'Facebook',
  'Preferiti' => 'Favorites',
  'Aggiungi' => 'Add',
  'Impostazioni' => 'Settings',
  'cerca' => 'search',
  'categorie' => 'categories',
  'indietro' => 'back',
  'Cerca' => 'Search',
  'filtri' => 'filters',
  'Nome *' => 'Name *',
  'Indirizzo' => 'Address',
  'Numero civico' => 'Address number',
  'CAP' => 'ZIP',
  'Citta' => 'City',
  'Stato' => 'Country',
  'Descrizione' => 'Description',
  'Telefono' => 'Phone',
  'SALVA' => 'SAVE',
  'Email *' => 'Email *',
  'Messaggio *' => 'Message *',
  'INVIA' => 'SEND',
  'ANNULLA' => 'CANCEL',
  'Vota' => 'Rate',
  'Modifica mappa' => 'Edit Map',
  'Utente' => 'User',
  'Logout' => 'Logout',
  'Login' => 'Login',
  'Raggio d\'azione' => 'Range',
  'Posizione dispositivo' => 'Device location',
  'Altro' => 'More',
  'Come usare PagineBaby' => 'How to use PagineBaby',
  'Credits' => 'Credits',
  'Pagine Baby è un progetto della cooperativa' => 'Baby Pages is a project of the cooperative',
  'This app is made by' => 'This app is made ​​by',
  'Come usare' => 'How to use',
  'Come usare txt' => '<p>Pagine Baby trova gli indirizzi più vicini alla posizione rilevata o impostata da te; le strutture
                                        in Primo Piano sono in cima alla lista.<br /><br />

                                        Cerca tutti gli indirizzi vicino a te o per Categorie; utilizza il tasto Cerca se sai esattamente
                                        cosa ti serve. Puoi inserire una parola chiave; ricorda che la ricerca è più efficace se elimini
                                        l’ultima lettera che definisce il singolare, il plurale o il genere (es. inserisci "passeggin" per
                                        trovare "passeggini" e "passeggino").<br /><br />
                                        
                                        Se conosci una struttura d’interesse o se ne sei il titolare, puoi usare la funzione Aggiungi per
                                        inserirla in Pagine Baby.<br /><br />
                                        
                                        Se sei il titolare di una struttura già presente, puoi rivendicarne la proprietà e modificare i
                                        dati se necessario.</p>',
); 
 ?>